### ISSUE TITLE
Clean install. Not working

### ISSUE THREAD

**Issue by nordic** [ligershark/webdevchecklist.com#57]
Hi, after clean install on the web i get this message. 
The given key was not present in the dictionary.

Description: An unhandled exception occurred during the execution of the current web request. Please review the stack trace for more information about the error and where it originated in the code. 

Exception Details: System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary.

Source Error:

 Line 15: string DataName = Checklist.GetPageName(Request).Replace("/", " ").Replace("index", string.Empty); Line 16: string Section = Checklist.GetBaseName(Request); Line 17: string PageTitle = Checklist.GetPageTitle(Request); Line 18: } Line 19:

**Comment by madskristensen** [comment]
Fixed. The site is now completely static
